# Generated by Django 5.2.3 on 2025-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('role', models.CharField()),
                ('image', models.FileField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
