# Generated by Django 5.2.3 on 2025-06-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_internshiphiring_servicehiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshiphiring',
            name='duration',
            field=models.CharField(default='2 months', max_length=100),
        ),
    ]
